"""empty message

Revision ID: eb5d505c0d56
Revises: 0cc45656bb83
Create Date: 2020-07-13 07:54:45.386210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb5d505c0d56'
down_revision = '0cc45656bb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.drop_table('actors_movies_relation')
    op.drop_table('actor')
    op.drop_table('movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('movie_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('release', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='movie_pkey'),
    sa.UniqueConstraint('title', name='movie_title_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('actor',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('actor_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='actor_pkey'),
    sa.UniqueConstraint('name', name='actor_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('actors_movies_relation',
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], name='actors_movies_relation_actor_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='actors_movies_relation_movie_id_fkey'),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id', name='actors_movies_relation_pkey')
    )
    op.drop_table('movies')
    op.drop_table('actors')
    # ### end Alembic commands ###
